version: '3.5'
services:
  api-postgres:
    container_name: api-postgres
    build: .
    ports:
      - 4000:4000
    environment:
      POSTGRES_HOST: postgres:postgres@postgres:5432
      PORT: 4000
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  web-client:
    container_name: web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    ports:
      - 3000:3000

networks:
  boilerplate-network:
    driver: bridge